import { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Footer from "@/Components/footer";
import Navbar from "@/Components/navbar";
import Game from "@/Components/game/game";
import Modal from "@/Components/modal";

export default function Home() {
  return (
    <>
      <Modal />
      <Head>
        <title>TSTetris</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1 className="text-6xl font-bold text-center">TSTetris</h1>
        <div className="flex justify-center">
          <Game />
        </div>
      </main>
      <Footer />
    </>
  );
}